Developing a library for Great Cow BASIC
 
Contents
Principles	3
Include statements	4
Header	5
Constants	6
Variables	7
Methods	8
Initialisation	9
PIC and AVR coexistence	10
Communication Protocols	11
Acceptance to mainline release	12




**Principles**

There are some basic rules when developing libraries.  They are very obvious but I will state for clarity.
----
    Keep constants and variable names unique in the library.
    Pass variables as parameter to the methods in the libraries – do not assume use of global variables.
    Use Sub and Function with overload functionality to manage the differing parameters.
    Use Macro(s) when required to improve performance.
    Use a Script to calculate constant values.
    Use an initialisation method to initialisation the library.
----

**Include statements**

Great Cow BASIC like other programming languages have a directive, called include that causes the contents of a second file to be inserted into the original source file.   These included files are called copybooks or header files.   They are often used to define the physical layout of program data, pieces of procedural code and/or forward declarations while promoting encapsulation and the reuse of code.

The include directive allows libraries of code to be developed which help to:

1.	Ensure that everyone uses the same version of a data layout definition or methods throughout a program.
2.	Simplify support by clearing identifying where components are used in a system.
3.	To enable easy change programs when needed (only one master file to change).

Includes provide additional capabilities to extend Great Cow BASIC.  There are two methods to include these capabilities.

1.	Include from distribution
2.	Include from a local installation

To use an include from the distribution, use the following.   You must use the `<` and `>` open and close brace to ensure you are using the distribution libraries.

----
    'include the GLCD libraries
    #include <glcd.h>
----

To use an include from the local installation, use the following.   You must use the `"` and `"` open and close quotes to ensure you are using the local installation libraries.

----
    'include a gamecontroller library from the local folder.
    'The specific source folder for the lirary is detetemined by the main user program source library.
    #include "gamecontroller.h"

----

**Structure of library**

The structure of a library is a follows.  This is recommend structure and has a level of flexibiity where sections may be ommitted when no needed.

1. Header
2. Constants
3. Variables
4. Script
5. Methods - SUBs and FUNCTIONs
6. Initialisation - a specific SUBroutine.

The next sections detail the of each part of the structure.

**Header**

Why is header needed?  As Great Cow BASIC uses the GNU license.  The header https://www.gnu.org/licenses/gpl-howto.en.html

Something like this is adequate, depending on where you live:

/* Copyright (C) YoYoDyne Systems, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Elmer Fudd <efudd@yoyodyne.com>, September 1943
 */
(2016 update: The phrase "All Rights Reserved" used to be required in some nations but is now not legally needed most places. In some countries it may help preserve some of the "moral rights.")

This means you cant:
Copy the file
Print the file out, scan it and copy the image
Print the file out, take pictures of it and distribute the film
etc ...
However, take care to note that in some countries, there is no such thing as copyright. This is also completely in addition to a strong license that you ship with your product, which should go into greater detail.

These sort of 'license headers' are designed simply to alert someone who happens upon a file that they should not distribute it.

We use something very much like that in stuff that we have that needs to stay behind closed doors. For instance, it alerts someone to not post functions on Stack Overflow.

Someone who p0wns your dev server to get your code probably isn't going to pay attention to it, however. Note, again, what you're describing is NOT a license, it's a per file assertion of copyright and specifically stating that the code is proprietary.


**Constants**
Naming and usage

**Variables**
Scope, naming and passing

**Methods**
Naming

**Initialisation**
How to

**PIC and AVR coexistence**
How to

**Communication Protocols**
SPI, I2C etc

**Acceptance to mainline release**
Testing and all 000 chips, Help, demos
